learning_templates/basicapp/urls.py
from django.urls import path
from . import views

app_name = 'basicapp'
urlpatterns=[
    path('relative',views.relative_url,name='relative'),
    path('other',views.others,name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/',include('basicapp.urls'))
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'Hello World','number':100}
    return render(request,'basicapp/index.html',context_dict)

def relative_url(request):
    return render(request,'basicapp/relative_url.html')

def others(request):
    return render(request,'basicapp/others.html')

learning_templates/templates/basicapp/basic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <ul class="navbar-nav mr-auto">
          <li><a class="nav-link"href="{% url 'index' %}">Brand</a></li>
          <li><a class="nav-link"href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="nav-link"href="{% url 'basicapp:other' %}">Other</a></li>

        </ul>

      </div>

    </nav>
    <div class="container">
      {% block body_block %}
      <!-- anything outside of this will be inherited -->
      {% endblock %}
    </div>

  </body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
{% load my_extra %}
{% extends "basicapp/basic.html" %}
  {% block body_block %}
  <h1>Welcome to index.html page</h1>
    <h1>{{text|cut:'World'}}</h1>
    <h1>{{number|add:100}}</h1>
  {% endblock %}

learning_templates/templates/basicapp/others.html
<!DOCTYPE html>
 {% extends "basicapp/basic.html" %}
  {% block body_block %}
    <h1>Welcome to others.html page</h1>
    <h2>Example of template inheritence</h2>
    {% endblock %}

learning_templates/templates/basicapp/relative_url.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative_url.html page</h1>
    <a href="{% url 'basicapp:other'%}">The Other Page</a>
    <a href="{% url 'admin:index' %}">Linked to admin page</a>
    <a href="{% url 'index'%}">Linked to index page</a>
  </body>
</html>